name: dart_wing_mobile
description: "DartWing Mobile"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.2

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.6
  json_annotation: ^4.9.0
  intl: ^0.20.2
  mobile_scanner: ^7.0.1
  easy_localization: ^3.0.7+1
  loader_overlay: ^5.0.0
  loading_overlay: ^0.4.2 # Replace it to loader_overlay
  sidebarx: ^0.17.1
  flutter_appauth: ^7.0.1
  flutter_secure_storage: ^9.2.2
  http: ^1.2.2
  jwt_decode: ^0.3.1
  upgrader: ^12.1.0
  package_info_plus: ^9.0.0
  email_validator: ^3.0.0
  flutter_svg: ^2.0.17
  flutter_multi_formatter: ^2.13.0
  url_launcher: ^6.3.1
  flutter_simple_treeview: ^3.0.2
  image_picker: ^1.1.2
  tflite_flutter: ^0.11.0
  image: ^4.5.4
  camera: ^0.11.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  assets:
    - lib/dart_wing/gui/images/
    - lib/dart_wing/localization/
